name: Continuous integration
on:
  create:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: PHP ${{ matrix.php }} 
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
      - name: Run tests
        run: |
          bash phplint.sh
  notify-irc:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: success
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#mediawiki-cosmos"
          nickname: miraheze-github
          message: |
            ${{ github.repository }} - ${{ github.actor }} The build passed.
      - name: failed
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#mediawiki-cosmos"
          nickname: miraheze-github
          message: |
            ${{ github.repository }} - ${{ github.actor }} the build has errored.
      - name: cancelled
        if: steps.wait-for-build.outputs.conclusion == 'cancelled'
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#mediawiki-cosmos"
          nickname: miraheze-github
          message: |
            ${{ github.repository }} - ${{ github.actor }} the build has been cancelled.
