on:
  create:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: PHP ${{ matrix.php }} 
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
      - name: Run tests
        run: |
          bash phplint.sh

  irc:
        name: IRC Notifications
        needs: build
        runs-on: ubuntu-latest
        if: ${{ always() }}
        steps:
          - name: The build has passed
          - uses: technote-space/workflow-conclusion-action@v2
          - uses: rectalogic/notify-irc@v1
            if: env.WORKFLOW_CONCLUSION == 'success' || env.WORKFLOW_CONCLUSION == 'failure' || env.WORKFLOW_CONCLUSION == 'cancelled'
            with:
              channel: "#mediawiki-cosmos"
              nickname: miraheze-github-notifier
              message: |
                ${{ github.actor }} the build has ${{ env.WORKFLOW_CONCLUSION }}
          - name: The build has failed
          - uses: rectalogic/notify-irc@v1
            if: ${{ failure() }}
            with:
              channel: "#mediawiki-cosmos"
              nickname: miraheze-github-notifier
              message: |
                ${{ github.actor }} the build has failed
          - name: The build has been cancelled
          - uses: rectalogic/notify-irc@v1
            if: ${{ cancelled() }}
            with:
              channel: "#mediawiki-cosmos"
              nickname: miraheze-github-notifier
              message: |
                ${{ github.actor }} the build has been cancelled
