on:
  create:
  push:
  pull_request:

jobs:
  notify-irc:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: success
        uses: technote-space/workflow-conclusion-action@v2
      - uses: rectalogic/notify-irc@v1
        if: env.WORKFLOW_CONCLUSION == 'success'
        with:
          channel: "#mediawiki-cosmos"
          nickname: miraheze-github
          message: |
            ${{ github.repository }} - ${{ github.actor }} The build passed.
      - name: failure
        uses: technote-space/workflow-conclusion-action@v2
      - uses: rectalogic/notify-irc@v1
        if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          channel: "#mediawiki-cosmos"
          nickname: miraheze-github
          message: |
            ${{ github.repository }} - ${{ github.actor }} the build has errored.
      - name: cancelled
        uses: technote-space/workflow-conclusion-action@v2
      - uses: rectalogic/notify-irc@v1
        if: env.WORKFLOW_CONCLUSION == 'cancelled'
        with:
          channel: "#mediawiki-cosmos"
          nickname: miraheze-github
          message: |
            ${{ github.repository }} - ${{ github.actor }} the build has been cancelled.
