on:
  create:
  push:
  pull_request:

jobs:
  build:
    if: github.event_name == 'create'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: PHP ${{ matrix.php }} 
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
      - name: Run tests
        run: |
          bash phplint.sh
